#+TITLE:Renting Agency Application

An application for managing renting agencies

* Specifications [5/8]
1. [X] Create tables (as per the design you showed) with necessary constraints.
2. [ ] Enter dummy data into the tables. We expect reasonable number of tuples for each table.
3. [X] Write a Stored Procedure to enter a record for property. Name of the stored procedure is ~InsertPropertyRecord~ (with necessary arguments/parameters for the attributes of the record).
4. [X] Write a Stored Procedure to display the properties (with all details) for a given ownerID. Name of the stored procedure is ~GetPropertyRecords~ (with Owner ID as the parameter).
5. [ ] Write a stored procedure to Print the tenant details for a given property. Name of the stored procedure is ~GetTenantDetails~ (with property id as the argument).
6. [X] Write a Stored Procedure to enter a record for a new User. Name of the stored procedure is ~CreateNewUser~ (with necessary arguments/parameters for the attributes like- user name, address, login credentials etc. of the record).
7. [X] Write a stored procedure that prints details of properties available in a city/locality. Name of the stored procedure is ~SearchProperyForRent~ (with city/locality as the argument).
8. [ ] Write a stored procedure to print the rent history for a given property. Name of the stored procedure is ~GetRentHistory~ (with property id as the argument).

9. Each group will bring its laptop for demonstration. No paperwork expected. But bring the details of your table design/ER diagram shown during the phase-1 evaluation, for cross verification.
10. During the evaluation, we will ask you to execute stored procedures (randomly) at the SQL command prompt, by giving some random values for parameters. We may also ask you to explain the code of any random stored procedure you have written. No front-end is needed.
11. We will randomly ask a few viva questions (similar to what we did during the Phase-1 evaluations).
12. We expect above functionality. But, to make the project more elegant/complete, you may add things as per your interest, but we will not give any weightage to that extra work.
13. If you have doubts, ask towards the end of lecture on Monday. DO NOT EMAIL me for clarity.
